#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

second_monitor=$(xrandr --query | grep 'DP-4')
if [[ $second_monitor = *connected* ]]; then
    xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --output DP-4 --mode 1920x1080 --rotate normal --right-of DP-2
fi

setxkbmap -model abnt2 -layout br &
light-locker --no-lock-on-suspend &
/usr/bin/dunst &
bash ${HOME}/.config/polybar/launch.sh --forest &
nitrogen --restore
picom --no-fading-openclose &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^6'
bspc rule -a Spotify desktop='^2'
