#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -model abnt2 -layout br &
light-locker &
/usr/bin/dunst &
bash ${HOME}/.config/polybar/launch.sh --forest &
nitrogen --restore
picom --no-fading-openclose &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^6'
bspc rule -a Spotify desktop='^2'
