vim.api.nvim_set_keymap('n', '<leader>dd', ':call vimspector#Launch()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>de', ':call vimspector#Reset()<CR>', { noremap = true, silent = true })

vim.api.nvim_set_keymap('n', '<leader>dbp', ':call vimspector#ToggleBreakpoint()<CR>', { noremap = true, silent = true })
-- vim.api.nvim_set_keymap('n', '<leader>dcbp', ':call vimspector#ToggleBreakpoint({condition = vim.fn.input("Expression > ")})<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dcl', ':call vimspector#ClearBreakpoints()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dw', ':call vimspector#AddWatch()<CR>', { noremap = true, silent = true })

vim.api.nvim_set_keymap('n', '<leader>drc', ':call vimspector#RunToCursor()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dl', ':call vimspector#StepInto()<CR>', { noremap = true, silent = true })
-- vim.api.nvim_set_keymap('n', '<F11>', ':call vimspector#StepInto()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dj', ':call vimspector#StepOver()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<F10>', ':call vimspector#StepOver()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>dk', ':call vimspector#StepOut()<CR>', { noremap = true, silent = true })
-- vim.api.nvim_set_keymap('n', '<F12>', ':call vimspector#StepOut()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>d<space>', ':call vimspector#Continue()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<F5>', ':call vimspector#Continue()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>ds', ':call vimspector#Stop()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<F3>', ':call vimspector#Stop()<CR>', { noremap = true, silent = true })

-- vim.api.nvim_set_keymap('n', '<leader>dK', '<Plug>VimspectorBalloonEval<CR>', { noremap = true, silent = true })
